// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// apa102 //
// ------ //

#define apa102_wrap_target 0
#define apa102_wrap 1

static const uint16_t apa102_program_instructions[] = {
            //     .wrap_target
    0x6001, //  0: out    pins, 1         side 0     
    0xb042, //  1: nop                    side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program apa102_program = {
    .instructions = apa102_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config apa102_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + apa102_wrap_target, offset + apa102_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif
